name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'bin_prebuilt/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'bin_prebuilt/**'
      - '**.md'

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    name: Linux Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug]
            clang_version: [clang++-14]

    steps:
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.clang_version}} Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -j 2
