name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'bin_prebuilt/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'bin_prebuilt/**'
      - '**.md'

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    name: Linux Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release]
            clang_version: [clang++-12, clang++-14]
            double_precision: [No, Yes]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.clang_version}} -DDOUBLE_PRECISION=${{matrix.double_precision}} Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -j 2

  linux-gcc:
    runs-on: ubuntu-22.04
    name: Linux GCC
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release]
            clang_version: [g++]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.clang_version}} Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_${{matrix.build_type}}_${{matrix.clang_version}} -j 2

  msvc_clang:
    runs-on: windows-latest
    name: Visual Studio Clang
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/VS2022_Clang -G "Visual Studio 17 2022" -A x64 -T ClangCL Build
    - name: Build
      run: msbuild Build\VS2022_Clang\OPENXR_PROVIDER.sln /property:Configuration=${{matrix.build_type}}
